# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: echung <echung@student.42seoul.kr>         +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/07/17 02:04:23 by echung            #+#    #+#              #
#    Updated: 2021/07/17 02:32:30 by echung           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

all:
	gcc -L ../mlx -lmlx -framework OpenGL -framework AppKit main.c -o test_load.out
	./test_load.out

clean:
	rm -rf *.out
